# SPDX-FileCopyrightText: Copyright (c) 2026 Max Fu
# SPDX-License-Identifier: MIT
#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from aspire.sim.cap.envs.tasks.base import CodeExecutionEnvBase

PROMPT = """
You are controlling a Franka Emika robot with API described below.
Goal: wipe up the 'brown spill'.
A sponge is already attached to your gripper/end-effector.
The table surface height is exactly z = 0.0 m, and wiping should be performed at that height (no extra offset).
Use the spill extents to inform the min/max x and y bounds of wiping motions.
Avoid large wiping motions since large deltas between inverse kinematics solutions may not guarantee optimal trajectories.
A sponge is already attached to the end-effector, and you should use a downward-facing orientation (0,0,1,0 wxyz) for wiping.
You may write python code comments for reasoning but ONLY write the executable Python code and do not write it in code fences.
The functions (APIs) below are already imported to the environment. If you want to use numpy, you need to import it explicitly.
"""
# Below oracle code was actually generated by GPT-OSS-20B lol kinda OP
ORACLE_CODE = """
import numpy as np

# Get the pose and bounding box of the brown spill
spill_pos, _, spill_extent = get_object_pose("brown spill", return_bbox_extent=True)

# Use downward-facing orientation as specified
down_quat = np.array([0.0, 0.0, 1.0, 0.0])

# Extract center and extents
center_x, center_y, _ = spill_pos
extent_x, extent_y, _ = spill_extent

# Compute min/max bounds in x and y (axis-aligned approximation)
min_x = center_x - extent_x / 2.0
max_x = center_x + extent_x / 2.0
min_y = center_y - extent_y / 2.0
max_y = center_y + extent_y / 2.0

# Limit step to around 0.05 m
step = 0.05

# Generate a simple back-and-forth wiping pattern over the spill area
x_positions = np.arange(min_x, max_x + step, step)
y_positions = np.arange(min_y, max_y + step, step)

# Set wiping height exactly at table surface
z_wipe = 0.0

# Approach height above table to move safely between wipes
z_approach = 0.10

# Start: move above the first wipe point
start_pos = np.array([x_positions[0], y_positions[0], z_approach])
goto_pose(start_pos, down_quat)

# Perform wiping passes along x, stepping along y
for i, y in enumerate(y_positions):
    # Determine direction of this pass (back-and-forth)
    if i % 2 == 0:
        x_traj = x_positions
    else:
        x_traj = x_positions[::-1]
    # Move above the start of this pass
    pass_start = np.array([x_traj[0], y, z_approach])
    goto_pose(pass_start, down_quat)
    # Move down to wiping height at start of pass
    pass_start_wipe = np.array([x_traj[0], y, z_wipe])
    goto_pose(pass_start_wipe, down_quat)
    # Wipe along the x direction at table height
    for x in x_traj[1:]:
        wipe_pos = np.array([x, y, z_wipe])
        goto_pose(wipe_pos, down_quat)
    # Move back up after each pass
    pass_end_approach = np.array([x_traj[-1], y, z_approach])
    goto_pose(pass_end_approach, down_quat)
"""


# ---------------------------- High-level Env -----------------------------
class FrankaSpillWipeCodeEnv(CodeExecutionEnvBase):
    """High-level code environment for Franka spill wipe using SimpleExecutor."""

    prompt = PROMPT
    oracle_code = ORACLE_CODE


__all__ = [
    "FrankaSpillWipeCodeEnv",
]
