#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Auto-generate docs/progress/fix_loop_robosuite_progress.md from filesystem state.

Run: .venv-robosuite/bin/python3 scripts/robosuite/gen_progress_robosuite.py
     (or append --print to stdout only, without writing the file)

The coordinator should run this instead of manually editing fix_loop_robosuite_progress.md.
Status is derived purely from disk — no agent memory involved.

The fix loop only produces fix_code.py (debug seeds 101-125).
Eval on seeds 1-100 is run manually by the user and is NOT tracked here.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIX_LOOP_ROOT = ROOT / "outputs/robosuite_fix_loop"
OUT_FILE = ROOT / "docs/progress/fix_loop_robosuite_progress.md"

TASKS = {
    "cube_lifting":     "cube_lifting_multimodel_aspire_traced",
    "cube_restack":     "cube_restack_multimodel_aspire_traced",
    "cube_stack":       "cube_stack_multimodel_aspire_traced",
    "nut_assembly":     "nut_assembly_multimodel_aspire_traced",
    "spill_wipe":       "spill_wipe_multimodel_aspire_traced",
    "two_arm_handover": "two_arm_handover_multimodel_aspire_traced",
    "two_arm_lift":     "two_arm_lift_multimodel_aspire_traced",
}


def is_blocked(task_dir: Path) -> bool:
    return (task_dir / "BLOCKED").exists()


def get_status(task_dir: Path, fix_code: Path) -> str:
    if is_blocked(task_dir):
        return "blocked"
    if fix_code.exists():
        return "done"
    return "pending"


def main():
    lines = []
    lines.append("# Fix Loop Progress — Robosuite")
    lines.append("")
    lines.append("*Auto-generated by `scripts/robosuite/gen_progress_robosuite.py` — do not edit manually.*")
    lines.append("**Status key:** `done` fix_code.py written | `blocked` all seeds blocked | `pending` not started")
    lines.append("")

    pending_tasks = []
    rows = []

    for task in sorted(TASKS):
        task_dir = FIX_LOOP_ROOT / task
        fix_code = task_dir / "fix_code.py"
        status = get_status(task_dir, fix_code)

        rows.append((task, status))

        if status == "pending":
            pending_tasks.append(task)

    if pending_tasks:
        lines.append("## Next Up")
        lines.append("")
        lines.append("**Pending** (no fix_code.py yet):")
        for t in pending_tasks:
            lines.append(f"- {t}")
        lines.append("")
        lines.append("---")
        lines.append("")

    done = sum(1 for _, s in rows if s == "done")
    total = len(rows)
    lines.append(f"## Robosuite  ({done}/{total} done)")
    lines.append("")
    lines.append("| Task | Status |")
    lines.append("|---|---|")
    for task, status in rows:
        lines.append(f"| {task} | {status} |")
    lines.append("")

    output = "\n".join(lines)

    print_only = "--print" in sys.argv
    if print_only:
        print(output)
    else:
        OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = OUT_FILE.with_suffix(".tmp")
        tmp.write_text(output)
        tmp.rename(OUT_FILE)
        print(f"Written: {OUT_FILE}")

    print(f"Progress: {done}/{total} tasks done  |  {len(pending_tasks)} pending")


if __name__ == "__main__":
    main()
