# Usage: uv run --no-sync --active python -m aspire.sim.cap.envs.launch --config-path env_configs/r1pro/r1pro_pick_up_radio_oracle.yaml

env:
  _target_: aspire.sim.cap.envs.tasks.r1pro.r1pro_pickup_radio.R1ProRadioCodeEnv
  cfg:
    _target_: aspire.sim.cap.envs.tasks.base.CodeExecEnvConfig
    # low_level: r1pro_b1k_low_level
    low_level:
      _target_: aspire.sim.cap.envs.simulators.r1pro_b1k.R1ProBehaviourLowLevel
      controller_cfg: r1pro_primitives_radio.yaml
    privileged: false
    apis:
      - R1ProControlApi
    # prompt is inherited from R1ProRadioCodeEnv class default

api_servers:
  - _target_: aspire.sim.cap.serving.launch_sam3_server.main
    device: cuda
    port: 8114
    host: 127.0.0.1

  - _target_: aspire.sim.cap.serving.launch_contact_graspnet_server.main
    port: 8115
    host: 127.0.0.1


record_video: true
output_dir: ./outputs/pick_up_radio_oracle

trials: 20
resume_idx: 1
num_workers: 1
use_oracle_code: true