#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Auto-generate docs/progress/libero_long_pro_progress.md from filesystem state.

Run: .venv/bin/python3 scripts/libero/gen_progress_long.py
     (or append --print to stdout only, without writing the file)

Tracks the LIBERO Long Pro (libero_10_swap + libero_10_task) actor pipeline.
Status derived purely from disk — no agent memory involved.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT      = Path(__file__).resolve().parents[2]
ACTOR_DIR = ROOT / "outputs/aspire_libero_long_actor"   # Stage 1: fix_code.py lives here
EVAL_DIR  = ROOT / "outputs/aspire_libero_long_eval"    # Stage 2: trial dirs land here
OUT_FILE  = ROOT / "docs/progress/libero_long_pro_progress.md"

SUITES = [
    "libero_10_swap",
    "libero_10_task",
]

DONE_THRESHOLD = 45  # unique seeds 1-50 on disk to consider Stage 2 complete

_TRIAL_RE = re.compile(r"trial_(\d+)_sandboxrc_\d+_reward_[\d.]+_taskcompleted_(\d+)")


def _parse_trial_dirs(outdir: Path) -> dict[int, list[tuple[float, int]]]:
    """Return {seed: [(mtime, completed), ...]} for seeds 1–50 under outdir."""
    if not outdir.exists():
        return {}
    result = subprocess.run(
        ["find", str(outdir), "-maxdepth", "5", "-type", "d", "-name", "trial_*"],
        capture_output=True, text=True, timeout=60,
    )
    seed_runs: dict[int, list[tuple[float, int]]] = {}
    for line in result.stdout.strip().split("\n"):
        if not line:
            continue
        p = Path(line)
        m = _TRIAL_RE.search(p.name)
        if not m:
            continue
        seed = int(m.group(1))
        if not (1 <= seed <= 50):
            continue
        completed = int(m.group(2))
        mtime = p.stat().st_mtime
        seed_runs.setdefault(seed, []).append((mtime, completed))
    return seed_runs


def _best_pass(runs: list[tuple[float, int]]) -> int:
    if not runs:
        return 0
    first = min(runs, key=lambda r: r[0])[1]
    last  = max(runs, key=lambda r: r[0])[1]
    return max(first, last)


def is_blocked(task_actor_dir: Path) -> bool:
    return (task_actor_dir / "BLOCKED").exists()


def get_status(task_actor_dir: Path, fix_code: Path, trials: int) -> str:
    if is_blocked(task_actor_dir):
        return "blocked"
    if trials >= DONE_THRESHOLD:
        return "done"
    if fix_code.exists():
        return "stage1-done"
    return "pending"


def fmt_rate(passes: int, trials: int) -> str:
    if trials == 0:
        return "—"
    pct = passes * 100 // trials
    return f"{passes}/{trials} ({pct}%)"


def shorten(task: str) -> str:
    t = task
    # strip scene prefix
    t = re.sub(r"^[A-Z_]+SCENE\d+_", "", t)
    t = t.replace("_", " ")
    return t[:60]


def main():
    lines = []
    lines.append("# LIBERO Long Pro — Actor Pipeline Progress")
    lines.append("")
    lines.append("*Auto-generated by `scripts/libero/gen_progress_long.py` — do not edit manually.*")
    lines.append("**Status key:** `done` ≥45 trials | `stage1-done` fix_code.py exists, Stage 2 not run | `blocked` all seeds blocked | `pending` not started")
    lines.append("")

    pending_tasks    = []
    stage1_done_tasks = []

    suite_rows = {}
    for suite in SUITES:
        # Task list comes from the LIBERO benchmark (not filesystem, since no baseline dir)
        try:
            from libero import benchmark as libero_benchmark
            bdict = libero_benchmark.get_benchmark_dict()
            task_suite = bdict[suite]()
            task_names = [task_suite.get_task(i).name for i in range(task_suite.n_tasks)]
        except Exception:
            # fallback: scan actor dir
            actor_suite_dir = ACTOR_DIR / suite
            if not actor_suite_dir.exists():
                continue
            task_names = sorted(p.name for p in actor_suite_dir.iterdir() if p.is_dir())

        rows = []
        for task in sorted(task_names):
            task_actor_dir = ACTOR_DIR / suite / task
            fix_code      = task_actor_dir / "fix_code.py"
            eval_task_dir  = EVAL_DIR / suite / task
            seed_runs      = _parse_trial_dirs(eval_task_dir)
            trials         = len(seed_runs)
            passes         = sum(_best_pass(r) for r in seed_runs.values())
            status         = get_status(task_actor_dir, fix_code, trials)
            rate           = fmt_rate(passes, trials) if trials > 0 else "—"
            rows.append((task, status, rate, passes, trials))

            if status == "pending":
                pending_tasks.append(f"{suite}/{task}")
            elif status == "stage1-done":
                stage1_done_tasks.append(f"{suite}/{task}")

        suite_rows[suite] = rows

    # Summary at top
    if pending_tasks or stage1_done_tasks:
        lines.append("## Next Up")
        lines.append("")
        if stage1_done_tasks:
            lines.append("**Stage 2 needed** (fix_code.py exists, run eval seeds 1–50):")
            for t in stage1_done_tasks:
                lines.append(f"- {t}")
            lines.append("")
        if pending_tasks:
            lines.append("**Pending** (no fix_code.py yet):")
            for t in pending_tasks:
                lines.append(f"- {t}")
        lines.append("")
        lines.append("---")
        lines.append("")

    for suite in SUITES:
        rows = suite_rows.get(suite)
        if not rows:
            continue
        done  = sum(1 for _, s, *_ in rows if s == "done")
        total = len(rows)
        lines.append(f"## {suite}  ({done}/{total} done)")
        lines.append("")
        lines.append("| Task | Status | Rate |")
        lines.append("|---|---|---|")
        for task, status, rate, *_ in rows:
            lines.append(f"| {shorten(task)} | {status} | {rate} |")
        lines.append("")

    output = "\n".join(lines)

    print_only = "--print" in sys.argv
    if print_only:
        print(output)
    else:
        OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = OUT_FILE.with_suffix(".tmp")
        tmp.write_text(output)
        tmp.rename(OUT_FILE)
        print(f"Written: {OUT_FILE}")

    total_done  = sum(1 for s in SUITES for _, st, *_ in suite_rows.get(s, []) if st == "done")
    total_tasks = sum(len(suite_rows.get(s, [])) for s in SUITES)
    print(f"Progress: {total_done}/{total_tasks} tasks done  |  "
          f"{len(stage1_done_tasks)} need Stage 2  |  "
          f"{len(pending_tasks)} pending")


if __name__ == "__main__":
    main()
