#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Generate docs/progress/scaling_law_progress.md from filesystem state.

Usage:
  .venv/bin/python3 scripts/libero/gen_progress_scaling.py
  .venv/bin/python3 scripts/libero/gen_progress_scaling.py --print   # stdout only

To record token data for a completed chunk (appends to JSON before regenerating):
  .venv/bin/python3 scripts/libero/gen_progress_scaling.py \
      --chunk 3 --tokens-input 120000 --tokens-cache 450000 --tokens-output 8000

Status is derived purely from disk state in outputs/scaling_build/.
Token data is stored in docs/progress/scaling_law_state.json and persists
across regenerations.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT       = Path(__file__).resolve().parents[2]
BUILD_DIR  = ROOT / "outputs/scaling_build/libero_90"
ORDER_FILE = ROOT / "ordering.txt"
MD_FILE    = ROOT / "docs/progress/scaling_law_progress.md"
JSON_FILE  = ROOT / "docs/progress/scaling_law_state.json"

CHUNK_SIZE = 5


def load_ordering() -> list[str]:
    if not ORDER_FILE.exists():
        sys.exit(f"ERROR: {ORDER_FILE} not found — run ordering generation first")
    tasks = [t.strip() for t in ORDER_FILE.read_text().splitlines() if t.strip()]
    if len(tasks) != 90:
        sys.exit(f"ERROR: ordering.txt has {len(tasks)} tasks, expected 90")
    return tasks


def task_status(task: str) -> str:
    d = BUILD_DIR / task
    if (d / "task_code.py").exists():
        return "done"
    if (d / "BLOCKED").exists():
        return "blocked"
    return "pending"


def chunk_status(statuses: list[str]) -> str:
    if all(s in ("done", "blocked") for s in statuses):
        return "build_done"
    if any(s != "pending" for s in statuses):
        return "in_progress"
    return "pending"


def load_json() -> dict:
    if JSON_FILE.exists():
        return json.loads(JSON_FILE.read_text())
    return {"chunks": {}}


def save_json(data: dict) -> None:
    JSON_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = JSON_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2))
    tmp.rename(JSON_FILE)


def short(task: str, width: int = 60) -> str:
    return task[:width] if len(task) <= width else task[:width - 1] + "…"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--print", dest="print_only", action="store_true")
    parser.add_argument("--chunk", type=int, help="Chunk index (1-based) to record tokens for")
    parser.add_argument("--tokens-input",  type=int, default=0)
    parser.add_argument("--tokens-cache",  type=int, default=0)
    parser.add_argument("--tokens-output", type=int, default=0)
    args = parser.parse_args()

    tasks = load_ordering()
    n_chunks = len(tasks) // CHUNK_SIZE  # 18

    # Load persistent token data
    state = load_json()

    # Record token data for a specific chunk if requested
    if args.chunk is not None:
        key = str(args.chunk)
        state["chunks"].setdefault(key, {})
        state["chunks"][key]["tokens_input"]  = args.tokens_input
        state["chunks"][key]["tokens_cache"]  = args.tokens_cache
        state["chunks"][key]["tokens_output"] = args.tokens_output
        state["chunks"][key]["tokens_total"]  = (
            args.tokens_input + args.tokens_cache + args.tokens_output
        )
        save_json(state)

    # Build per-chunk data
    chunks = []
    for i in range(n_chunks):
        chunk_tasks = tasks[i * CHUNK_SIZE : (i + 1) * CHUNK_SIZE]
        statuses = [task_status(t) for t in chunk_tasks]
        cs = chunk_status(statuses)
        n_done    = statuses.count("done")
        n_blocked = statuses.count("blocked")
        n_pending = statuses.count("pending")
        tok = state["chunks"].get(str(i + 1), {})
        chunks.append({
            "i": i + 1,
            "tasks": chunk_tasks,
            "statuses": statuses,
            "status": cs,
            "n_done": n_done,
            "n_blocked": n_blocked,
            "n_pending": n_pending,
            "tokens": tok,
        })

    # Totals
    all_statuses = [task_status(t) for t in tasks]
    total_done    = all_statuses.count("done")
    total_blocked = all_statuses.count("blocked")
    total_pending = all_statuses.count("pending")
    chunks_done   = sum(1 for c in chunks if c["status"] == "build_done")

    # Current chunk = first non-build_done
    current_chunk = next((c["i"] for c in chunks if c["status"] != "build_done"), None)

    # --- Markdown ---
    lines = []
    lines.append("# LIBERO-90 Scaling-Law Build — Progress")
    lines.append("")
    lines.append("*Auto-generated by `scripts/libero/gen_progress_scaling.py` — do not edit manually.*")
    lines.append("")
    lines.append(f"**Chunks:** {chunks_done}/18 build_done  "
                 f"| **Tasks:** {total_done} done, {total_blocked} blocked, {total_pending} pending  "
                 f"| **Current chunk:** {current_chunk if current_chunk else 'ALL DONE'}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Chunk summary table
    lines.append("## Chunk Summary")
    lines.append("")
    lines.append("| Chunk | Tasks | Done | Blocked | Status | Tokens |")
    lines.append("|---|---|---|---|---|---|")
    for c in chunks:
        start = (c["i"] - 1) * CHUNK_SIZE + 1
        end   = c["i"] * CHUNK_SIZE
        tok_total = c["tokens"].get("tokens_total", "")
        tok_str = f"~{tok_total // 1000}k" if tok_total else "—"
        marker = " ◄" if c["i"] == current_chunk else ""
        lines.append(
            f"| {c['i']:2d} (tasks {start:2d}–{end:2d}) "
            f"| {CHUNK_SIZE} "
            f"| {c['n_done']} "
            f"| {c['n_blocked']} "
            f"| {c['status']}{marker} "
            f"| {tok_str} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-chunk detail
    lines.append("## Per-Chunk Detail")
    lines.append("")
    for c in chunks:
        marker = " ◄ CURRENT" if c["i"] == current_chunk else ""
        lines.append(f"### Chunk {c['i']}{marker}")
        lines.append("")
        lines.append("| # | Task | Status |")
        lines.append("|---|---|---|")
        for k, (task, status) in enumerate(zip(c["tasks"], c["statuses"])):
            global_idx = (c["i"] - 1) * CHUNK_SIZE + k + 1
            lines.append(f"| {global_idx:2d} | {short(task)} | {status} |")
        if c["tokens"]:
            t = c["tokens"]
            lines.append("")
            lines.append(
                f"*Tokens: input={t.get('tokens_input', 0):,}  "
                f"cache={t.get('tokens_cache', 0):,}  "
                f"output={t.get('tokens_output', 0):,}  "
                f"total={t.get('tokens_total', 0):,}*"
            )
        lines.append("")

    output = "\n".join(lines)

    if args.print_only:
        print(output)
    else:
        MD_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = MD_FILE.with_suffix(".tmp")
        tmp.write_text(output)
        tmp.rename(MD_FILE)
        print(f"Written: {MD_FILE}")
        print(f"Written: {JSON_FILE}")

    print(
        f"Progress: {chunks_done}/18 chunks done | "
        f"{total_done} tasks solved | {total_blocked} blocked | {total_pending} pending"
    )


if __name__ == "__main__":
    main()
