"""Strict opt-in entry for the CC engineering reference relational world.

This module exists so the schema4 relational mechanisms can be exercised online
with a world program whose authorship is stated honestly. It changes no world
mathematics and no adapter behaviour: the broker is ``RelationalSceneBroker``
byte-for-byte, and the world program is the already tested reference at
``cap/world_model/reference_relational_world.py`` pinned by digest.

Authorship, which every artifact of this mode must repeat without softening:

* ``world_program_generator: cc-engineering-reference`` — the relational world
  program was hand-written in a CC coordinator session with Opus 5 (high
  reasoning). It is NOT the missing artifact of the Opus 4.6 world-generation
  protocol and must never be recorded as one.
* ``policy_generator: claude-opus-4-6`` — the replayed policy is the frozen
  Opus 4.6 shared policy, unchanged.
* ``model_id: claude-opus-4-6`` — present only as the frozen action-policy
  replay identity, carried by the child request. It says nothing about who
  wrote the world program.

The original ``opus46-relational-scene-diagnostic`` loader keeps its own strict
Opus 4.6 provenance gate; nothing here relaxes, wraps, or patches it, and an
honestly labelled reference config is rejected by it.
"""
from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import re
import sys
from types import SimpleNamespace

from .live_broker import (SUITE, TASK, _child_environment, _launch_child,
                          _prepare_live, _sha256, _write_json)
from .relational_scene_broker import RelationalSceneBroker

MODE = "cc-reference-relational-scene-diagnostic"
PROFILE = "bowl-on-plate-cc-reference-relational-scene-dev"
SCHEMA = 5
WORLD_SHA = "63696bbf74bb1e3cf025a1f2d3518c6bc70699e9599b368f60f5e3c76621b4ab"
POLICY_SHA = "be5a7cb07f8e0d38892bfca4d424da08015efa56b484882aa2b6633a58da7ec2"
WORLD_GENERATOR = "cc-engineering-reference"
POLICY_GENERATOR = "claude-opus-4-6"
POLICY_REPLAY_MODEL_ID = "claude-opus-4-6"
MODEL_ID_ROLE = "frozen_action_policy_replay_identity_only"
DISCLOSURE = ("world program: CC engineering reference authored in this coordinator "
              "session with Opus 5 high; not an Opus 4.6 generated artifact; "
              "policy: frozen Opus 4.6 shared policy replayed unchanged")
CONTEXT_REQUIRED = ("cc engineering reference", "opus 5", "high", "policy")
CONTEXT_FORBIDDEN = ("world program generated by claude-opus-4-6", "opus 4.6 world",
                     "opus4.6 world", "opus46 world", "opus 4.6 generated world")

CONFIG_FIELDS = {"schema_version", "mode", "profile", "task_gate", "dev_seeds",
                 "world_program", "world_program_sha256", "policy_sha256",
                 "observation", "query_budget", "tolerance", "max_actions",
                 "max_recovery", "trial_timeout_seconds", "output_root", "run_name",
                 "model_provenance", "reference_disclosure", "scene_inventory",
                 "identity_binding", "query_schedule"}
PROVENANCE_FIELDS = {"model_id", "model_id_role", "policy_generator",
                     "world_program_generator", "generation_context"}
FIXED = {"schema_version": SCHEMA, "mode": MODE, "profile": PROFILE,
         "task_gate": {"suite": SUITE, "task": TASK}, "dev_seeds": [51, 65],
         "observation": {"object_id": "bowl", "segmentation_prompt": "bowl", "min_score": .5},
         "query_budget": 4, "tolerance": .03, "max_actions": 30, "max_recovery": 1,
         "trial_timeout_seconds": 900, "identity_binding": "unique_high_score_mask",
         "query_schedule": "close_reference_then_policy_verify",
         "reference_disclosure": DISCLOSURE}


def _check_provenance(prov):
    """Require honest, separated sources; never accept a forged Opus 4.6 world."""
    if not isinstance(prov, dict) or set(prov) != PROVENANCE_FIELDS:
        raise ValueError("invalid provenance fields")
    if prov["world_program_generator"] != WORLD_GENERATOR:
        raise ValueError("reference mode requires world_program_generator="
                         + WORLD_GENERATOR + "; the CC reference world must never "
                         "be recorded as an Opus 4.6 generated artifact")
    if prov["policy_generator"] != POLICY_GENERATOR:
        raise ValueError("reference mode replays the frozen Opus 4.6 policy only")
    if prov["model_id"] != POLICY_REPLAY_MODEL_ID or prov["model_id_role"] != MODEL_ID_ROLE:
        raise ValueError("model_id is the frozen action-policy replay identity only")
    context = prov["generation_context"]
    if not isinstance(context, str) or not 1 <= len(context) <= 400:
        raise ValueError("generation_context must be a short honest string")
    lowered = context.lower()
    if any(marker not in lowered for marker in CONTEXT_REQUIRED):
        raise ValueError("generation_context must state that the world program is a "
                         "CC engineering reference authored with Opus 5 high, and "
                         "name the policy source separately")
    if any(claim in lowered for claim in CONTEXT_FORBIDDEN):
        raise ValueError("generation_context must not claim Opus 4.6 world authorship")


def _check_inventory(inventory):
    if not isinstance(inventory, list) or not 2 <= len(inventory) <= 12:
        raise ValueError("scene inventory must contain 2-12 entities")
    ids = set()
    for entity in inventory:
        if not isinstance(entity, dict) or set(entity) != {"id", "label", "role", "confidence", "shape_prior"}:
            raise ValueError("scene entities must contain only semantic metadata")
        if (not all(isinstance(v, str) and v for v in entity.values())
                or not entity["id"].replace("_", "").isalnum() or entity["id"] in ids
                or len(entity["label"]) > 160 or entity["role"] not in {"manipulated", "target", "context"}):
            raise ValueError("invalid scene entity")
        ids.add(entity["id"])
    if ([e["id"] for e in inventory if e["role"] == "manipulated"] != ["bowl"]
            or [e["id"] for e in inventory if e["role"] == "target"] != ["plate"]):
        raise ValueError("scene roles must identify bowl and plate")


def load_reference_config(args):
    """Validate the strict reference profile; identities are pinned, not inferred."""
    if getattr(args, "api_key", None) or not args.replay_code or args.interactive:
        raise ValueError("reference replay requires frozen code, no API key, and noninteractive mode")
    if args.suite != SUITE or args.task != TASK or type(args.trial) is not int or not 51 <= args.trial <= 65:
        raise ValueError("reference profile permits bowl-on-plate development seeds 51-65 only")
    config = json.loads(Path(args.world_model_config).read_text())
    if not isinstance(config, dict) or set(config) != CONFIG_FIELDS:
        raise ValueError("unexpected reference configuration fields")
    for key, value in FIXED.items():
        if config.get(key) != value or isinstance(config.get(key), bool):
            raise ValueError("reference configuration differs from frozen protocol: " + key)
    if not isinstance(config["run_name"], str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", config["run_name"]):
        raise ValueError("run_name must be a single safe path component")
    world = Path(config["world_program"])
    if not world.is_absolute():
        world = Path(args.world_model_config).parent / world
    if (config["world_program_sha256"] != WORLD_SHA or not world.is_file()
            or _sha256(world) != WORLD_SHA):
        raise ValueError("world source must be the exact tested CC engineering reference program")
    if config["policy_sha256"] != POLICY_SHA or _sha256(Path(args.replay_code)) != POLICY_SHA:
        raise ValueError("policy source must match the frozen Opus 4.6 shared policy")
    config["world_program"] = str(world.resolve())
    _check_provenance(config["model_provenance"])
    _check_inventory(config["scene_inventory"])
    output = Path(config["output_root"]).expanduser().resolve()
    ordinary = Path(args.output_dir).expanduser().resolve()
    if output.is_relative_to(ordinary) or ordinary.is_relative_to(output):
        raise ValueError("reference evidence output must be separate from ordinary replay output")
    config["output_root"] = str(output)
    import yaml
    base = yaml.safe_load(Path(args.config).read_text())
    cfg = base.get("env", {}).get("cfg", {})
    if (cfg.get("privileged", False) or cfg.get("low_level", {}).get("privileged", False)
            or cfg.get("apis") != ["FrankaLiberoApiReducedSkillLibraryTraced"]):
        raise ValueError("reference replay requires the nonprivileged reduced traced API")
    return config, base


def run_reference_relational_scene(args):
    config, _ = load_reference_config(args)
    environment = _child_environment(dict(os.environ))
    request_path = _prepare_live(args, config)
    directory = request_path.parent
    request = json.loads(request_path.read_text())
    request["schema_version"] = SCHEMA
    _write_json(request_path, request)
    path = directory / "live_manifest.json"
    prepared = json.loads(path.read_text())
    prepared.update(schema_version=SCHEMA, mode=MODE, identity_binding=config["identity_binding"],
                    query_schedule=config["query_schedule"], generation_model_requests_this_trial=0,
                    world_program_generator=WORLD_GENERATOR, policy_generator=POLICY_GENERATOR,
                    model_id_role=MODEL_ID_ROLE, reference_disclosure=DISCLOSURE,
                    adapter_sha256=_sha256(Path(__file__)),
                    relational_adapter_sha256=_sha256(
                        Path(__file__).with_name("relational_scene_broker.py")))
    _write_json(path, prepared)
    receipt = _launch_child(request_path, environment, config["trial_timeout_seconds"],
                            module="cap.world_model.reference_scene_broker")
    try:
        manifest = json.loads(path.read_text())
        valid = (manifest.get("status") == "complete" and manifest.get("mode") == MODE
                 and manifest.get("schema_version") == SCHEMA
                 and manifest.get("world_program_generator") == WORLD_GENERATOR
                 and manifest.get("policy_generator") == POLICY_GENERATOR
                 and manifest.get("model_id_role") == MODEL_ID_ROLE
                 and manifest.get("model_provenance") == config["model_provenance"]
                 and manifest.get("reference_disclosure") == DISCLOSURE
                 and (manifest.get("suite"), manifest.get("task"), manifest.get("seed")) == (SUITE, TASK, args.trial)
                 and manifest.get("adapter_sha256") == prepared["adapter_sha256"] == _sha256(Path(__file__))
                 and manifest.get("relational_adapter_sha256") == prepared["relational_adapter_sha256"]
                 == _sha256(Path(__file__).with_name("relational_scene_broker.py"))
                 and manifest.get("world_program_sha256") == WORLD_SHA
                 and manifest.get("policy_sha256") == POLICY_SHA)
        for field, name in [("policy_sha256", "frozen_policy.py"), ("world_program_sha256", "world_program.py"),
                            ("live_config_sha256", "live_config.json"), ("yaml_sha256", "source_config.yaml"),
                            ("tape_sha256", "live_tape.jsonl")]:
            valid = valid and manifest.get(field) == _sha256(directory / name)
            if field != "tape_sha256":
                valid = valid and manifest.get(field) == prepared.get(field)
    except (OSError, ValueError, TypeError):
        valid = False
    receipt["manifest_valid"] = bool(valid)
    _write_json(directory / "child_exit.json", receipt)
    if receipt["status"] != "completed" or not valid:
        raise RuntimeError("reference trial child failed or evidence incomplete: " + str(directory))


def _child_main(request_path):
    directory = request_path.parent
    request = json.loads(request_path.read_text())
    if request.get("schema_version") != SCHEMA:
        raise ValueError("unsupported reference child schema")
    if _sha256(directory / "world_program.py") != WORLD_SHA:
        raise ValueError("child world source is not the tested CC engineering reference")
    if _sha256(directory / "frozen_policy.py") != POLICY_SHA:
        raise ValueError("child policy source is not the frozen Opus 4.6 policy")
    replay_path = Path(__file__).resolve().parents[2] / "scripts/libero/replay_trial.py"
    spec = importlib.util.spec_from_file_location("_reference_scene_world_replay", replay_path)
    replay = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = replay
    spec.loader.exec_module(replay)
    if os.environ.get("SAM3_SERVICE_URL"):
        from aspire.sim.cap.integrations.vision import sam3
        sam3.SERVICE_URL = os.environ["SAM3_SERVICE_URL"]
    if os.environ.get("PYROKI_SERVICE_URL"):
        from aspire.sim.cap.integrations.motion import pyroki
        pyroki.init_pyroki.__defaults__ = (os.environ["PYROKI_SERVICE_URL"],)
    broker = RelationalSceneBroker(directory, json.loads((directory / "live_config.json").read_text()),
                                   json.loads((directory / "live_manifest.json").read_text()),
                                   (directory / "world_program.py").read_text())
    error = None
    try:
        replay._run_replay(SimpleNamespace(**request["args"]), _world_capture=broker)
    except BaseException as exc:
        error = type(exc).__name__
        raise
    finally:
        broker.close(error)
    if broker.manifest["status"] != "complete":
        raise RuntimeError("reference world mechanism evidence incomplete")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--child-request", type=Path, required=True)
    _child_main(parser.parse_args().child_request.resolve())
